apiVersion: v1
kind: Service
metadata:
  name: tfm-microservice
  labels:
    app: tfm-microservice
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: tfm-microservice
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfm-microservice
  labels:
    app: tfm-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfm-microservice
  template:
    metadata:
      labels:
        app: tfm-microservice
    spec:
      containers:
      - name: tfm-microservice
        image: dcortesf/tfm-microservice:1.0
        env:
        - name: JAVA_APP_JAR
          value: "/deployments/quarkus-run.jar"
        - name: JAVA_OPTS
          value: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /nuclear/info
            port: 8080
